jobs:
  job_id: "my_job"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "google-github-actions/auth@v1"
        with:
          service_account: "ryparedes@cfl-gs-premiumsupport-ams.iam.gserviceaccount.com"

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: ">= 363.0.0"
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - id: "gce_instance"
        uses: "aplr/action-gcloud-compute-instance@v0.0.11"
        with:
          name_prefix: "my-instance"
          source_instance_template: "my-template"
          zone: "us-central1-a"
          project: "my-project"

      - name: "Use output"
        run: 'curl "${{ steps.gce_instance.outputs.instance_ip }}"'
